name: tests

on: 
    push:
        branches:
            - main

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1','8.2','8.3']
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"
        
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          coverage: none
          tools: composer, phpunit:8.5
          ini-values: "memory_limit=512M"
          # extensions: ${{ matrix.ffi }}

      - name: Install OpenBLAS
        run: |
          sudo apt install -y clinfo
          sudo apt install -y pocl-opencl-icd
          sudo apt install -y ocl-icd-opencl-dev

      - name: Build
        run: |
          composer update
          phpize${{ matrix.php }}
          mv build/Makefile.global build/Makefile.global.orig
          sed -f Makefile.global.patch < build/Makefile.global.orig > build/Makefile.global
          ./configure --enable-rindow_opencl --with-php-config=php-config${{ matrix.php }}
          make clean
          make

      - name: Tests
        run: |
          make test

      - name: Install rindow_opencl
        run: |
          sh ./packaging.sh ${{ matrix.php }}
          RINDOW_OPENCL_VERSION=`fgrep "# define PHP_RINDOW_OPENCL_VERSION" php_rindow_opencl.h | cut -d " " -f 4 | cut -d "\"" -f 2`
          . /etc/os-release
          sudo apt install -y ./rindow-opencl-php${{ matrix.php }}_${RINDOW_OPENCL_VERSION}-1+${ID}${VERSION_ID}_amd64.deb

